services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRAFANA_API_KEY=${GRAFANA_API_KEY}
    command: ["--config", "/etc/otel-collector-config.yaml"]
