version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Web UI
      - "14250:14250"  # gRPC collector
      - "14268:14268"  # HTTP collector
      - "6831:6831/udp"  # Jaeger thrift compact
      - "6832:6832/udp"  # Jaeger thrift binary
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge