receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "https://otlp-gateway-prod-ap-south-1.grafana.net:4317"
    headers:
       Authorization: "Bearer ${GRAFANA_API_KEY}"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
