name: Simple Go CI with Observability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Check OTEL endpoint
      run: curl -I ${{ secrets.GRAFANA_CLOUD_OTEL_ENDPOINT }}

    - name: Upload OTEL traces
      uses: MNThomson/otel-action@master
      with:
        endpoint: ${{ secrets.GRAFANA_CLOUD_OTEL_ENDPOINT }}
        headers: |
          Authorization: Basic ${{ secrets.GRAFANA_CLOUD_API_KEY }}
        service_name: "simple-go-project-ci"

    - name: Check OTEL action logs
      run: echo "OTEL action logs:" && cat /path/to/otel-action-logs
