name: CI Pipeline with OTel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Build and run Go application
      run: go run main.go

    - name: Upload OTEL traces
      uses: MNThomson/otel-action@master
      with:
        endpoint: ${{ secrets.ENDPOINT }}
        headers: '{"Content-Type": "application/json"}'
        service_name: "HelloWorld"
