name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OTEL_EXPORTER_JAEGER_ENDPOINT: ${{ secrets.JAEGER_ENDPOINT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the application
      run: go build -o myapp main.go

    - name: Run the application with OpenTelemetry
      run: ./myapp