name: CI Pipeline with Observability

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build
      run: go build -v ./...

    - name: Upload OTEL traces
      uses: MNThomson/otel-action@master
      with:
        endpoint: https://tempo-prod-19-prod-ap-south-1.grafana.net  # Grafana Cloud Tempo endpoint
        headers: '{"Authorization": "Bearer ${{ secrets.GRAFANA_API_KEY }}"}'  # Use a secret for the API key
        service_name: "simple-go-project-ci"  # Replace with your service name
