name: CI Pipeline with OpenTelemetry Tracing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OTEL_EXPORTER_JAEGER_ENDPOINT: ${{ secrets.JAEGER_ENDPOINT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the application
      run: go build -o pipeline_tracer main.go

    - name: Run the application and capture output
      run: |
        echo "Running pipeline tracer..."
        ./pipeline_tracer
      env:
        OTEL_EXPORTER_JAEGER_ENDPOINT: ${{ secrets.JAEGER_ENDPOINT }}

    - name: Check Jaeger endpoint
      run: |
        echo "Jaeger endpoint: $OTEL_EXPORTER_JAEGER_ENDPOINT"