name: CI with OpenTelemetry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Send data to OTLP
      uses: codeboten/github-action-to-otlp@v1
      with:
        endpoint: 'grpc://847b-2401-4900-1c82-4453-35f9-cc9-671a-e966.ngrok-free.app:443'