name: Simple Go CI with Observability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Upload OTEL traces
      uses: MNThomson/otel-action@master
      with:
        endpoint: https://8448-2401-4900-1c82-4453-dc7f-736d-e37b-2312.ngrok-free.app
        service_name: "simple-go-project-ci"
